apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nk35
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-nk35@sha256:8ac572c3f174a983093e50f6988610f7519a5c18564a8c1d8e2b8ad903e5930d
        name: my-nodejs
        resources: {}
status: {}
